name: Google Search Console Auto Commit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i -g google-indexing-script
    - run: gis flyandnotdown.github.io --client-email ${{ secrets.CLIENT_EMAIL }} --private-key ${{ secrets.PRIVATE_KEY }}
